language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
script: 
  - mvn package -nsu -DskipMunitTests --file pom.xml
  - echo $FINGERPRINT >> $HOME/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - scp $TRAVIS_BUILD_DIR/target/$JAR_FILE $SERVER_USER@$SERVER_IP:$MULE_HOME
  - ssh $SERVER_USER@$SERVER_IP sh $MULE_HOME/deploy.sh $JAR_FILE staging
