#%RAML 1.0 NamedExample
value:
  users:
    - 
      username: jlazim
      fullname: jabalnur Lazim
      birthday: 02-05-1990
      gender: male
    - 
      username: jlazim
      fullname: jabalnur Lazim
      birthday: 02-05-1990
      gender: male